# BroadCaster plugin config.

command:
  name: 'broadcast'
  description: 'Broadcast a message to all players.'
  usage: '/broadcast <message>'
  aliases: ['bc']
  permission:
    name: 'broadcast.use'
    default: 'operator'

unregister.say.command: false

# Interval de message destiné aux messages exéptionnels.
broadcastMessage.Interval: 300
broadcast:
  format: '§7[§6Broadcast§7] §f%message%' #Possibilité de mettre %player% pour afficher le nom du joueur.
  type: chat # popup actionbar, tip, chat

message.type: chat # popup, actionbar, tip, chat
broadcasts:
  0:
    message: 'Welcome to the server!'
    interval: 300